### ISSUE TITLE
No destination host name supplied by cups-browsed for printer, is cups-browsed running?

### ISSUE THREAD

**Issue by prlw1** [OpenPrinting/cups-filters#357] opened 2021-04-08 12:29 UTC
I have had this problem for a while, but waited until I could run cupsd 2.3.3op2 and cups-filters 1.28.7, so long after the patches in issue #97 were commited.

Networkwise, cupsd is running on a computer "cupsdAB" with a single network card with IP numbers on two class C networks, lets call them nets A and B.

There is a printerOK on net A, and a printerBAD on net B. (shame markup seems to munge my attempt at ascii diagrams)

There is unixclientA on net A, and a winclientB on net B.

Using cupdAB:631/printers/... for printers in windows on winclientB, winclientB can successfully print to printerOK and printerBAD.

unixcilentA, sees implicitclass queues for printerOK and printerBAD picked up via cups-browsed. The printerOK_cupsdAB queue is fine. The printerBAD_cupsdb queue says "No destination host name supplied"...

Just in case, I created ppds for both printers using "driverless", but no change. Protocols in the .conf files would affect both
printers equally. The only part that springs to mind is the network side, yet the winclientB can print to both printers.

**Comment by surajkulriya** [comment] 2021-05-12 14:03
hii @prlw1 
I went through comments of #97 and I think your issue is not related to issue 97 because the cause of the issue 97 was already solved in `cups-filters 1.22.2`. However, a similar issue to that of this one is still open (#343). The author of that issue came out with a temporary solution of 
```
service cups-browsed restart
service cups restart
```
Can you too please try this. It may solve your issue temporarily until we come out with a final and stable solution.
Many thanks :-)

**Comment by prlw1** [comment] 2021-05-17 11:02
Restarting cups-browsed and cups resulted in no change: briefly the printers status changed to "processing", but then the logs show "No destination..." as above, and "Backend returned status 4 (stop printer)".

**Comment by makuser** [comment] 2022-01-05 20:46
There are two different issues for the same bug, #357 and #429. What is the difference between them, because I have not been able to find one. Maybe one should be closed and marked as duplicate of the other.

I am running into the same issue on several machines running Ubuntu 20.04, I might be able to help out if any more information is needed. Is that the case, is there something to test out?

**Comment by TinyTrebuchet** [comment] 2022-01-28 19:22
Could you please attach the log files of cups-browsed and cups? Make sure to enable debug logging in both by:
1. Running command:
```
cupsctl --debug-logging
```
and then restarting cups.

2. Editing `/etc/cups/cups-browsed.conf` to include the line:
```
DebugLogging file
```
and then restarting cups-browsed.

Then attach the files `/var/log/cups/error_log` and `/var/log/cups/cups-browsed_log`. You might have to rename them with a '.txt' extension to upload them here.

**Comment by tillkamppeter** [comment] 2022-11-14 10:40
Closing, as request for more info from the original poster stayed unanswered.

**Closed** 2022-11-14 10:40 UTC

**Comment by makuser** [comment] 2023-05-02 16:22
> Closing, as request for more info from the original poster stayed unanswered.

It happens on every single Ubuntu 20.04 and also 22.04 machine I manage, what more info could I possibly supply, that the original poster missed, because they probably just gave up on this?
