### ISSUE TITLE
pdftopdf scaling regression in 1.28.x and 2.0.0

### ISSUE THREAD

**Issue by 10ne1** [OpenPrinting/cups-filters#549] opened 2023-09-27 10:25 UTC
Hello

**Describe the bug**
This [example doc](https://drive.google.com/file/d/11FNSQ5DzHIs3h3peZsZSnY4WuqX0A5cb/view) used to print fine until cups-filters v1.28.11, but starting with v1.28.12 the output [document is mangled](https://drive.google.com/file/d/1AYCZVpAZPM5pybo03KoVeHWSY7oxhOOT/view?usp=drive_link). Looks like a scaling issue.

If I checkout **v1.28.12** and revert the following commits introduced by 1.28.12, the document output is correct again, so one or maybe a combination of them is causing the regression, likely the two scaling commits:
```
ddd9da98fd8 pdftopdf: Add 2% tolerance for input size larger than output page
02e95494b49 pdftopdf: Set a default for "print-scaling"
207314fc3db pdftopdf: Fixed print-scaling and N-up for asymmetric margins and files with differently-sized pages
```

I have also reproduced this with the latest **v2.0.0**, this is why I think it is likely a real bug, not just a backporting problem on 1.28.12 - 1.28.17.

**To Reproduce**

Run the following command on the document linked above and compare the output
```
/usr/lib/cups/filter/pdftopdf 1 1 1 1 "" Example_1-page1-5.pdf > output.pdf
```

**Expected behavior**
The output should display the same as the input file, which used to happen in previous versions as described above., however the text is now very small in the bottom left corner.

**System Information:**
 - OS: Arch Linux x86_64 and ChromeOS aarch64
 - Browser: Chrome 119, Firefox 117

**Comment by tillkamppeter** [comment] 2023-12-12 18:51
Hi, could you repost or attach `example.doc`? Or at least allow access to it? Thanks.

**Comment by arunpatwa** [comment] 2024-03-24 10:33
@10ne1 Hi, I have build the cups-filter and reproduced the output.pdf which is mangling. I am facing issue when I checkout to 1.28.12 and reverting to the commit "ddd9da98fd8" and then on running "./configure" and "sudo make" , There are lots of dependencies errors. this is occuring when I checkout from master to 1.28.12 . some of the errors I have solved by checking the changes.. but still there are errors. How I can solve the errors while reverting the commits...

![image](https://github.com/OpenPrinting/cups-filters/assets/91215615/1fc2555f-7b51-4f65-a31a-1c61afce0b71)

**Comment by arunpatwa** [comment] 2024-03-24 19:46
Thanks for your active response @10ne1. This time , I have reverted all 3 commits. and then did "./autogen.sh",  "./configure" and "make" . I am still getting errors.
I am trying to fix these since 3-4 days but unfortunately did not find the way... errors are occurring when in **cups-filter** , I  switch from "master" branch to "1.28.12" there are lots of files/structure changes which are causing issue in building again.

Could you please try this on your device ? Is it also giving similar types of errors  or I am facing this issue.
It would be really helpful, so that can work on logical part of issue , instead of debugging errors.

I wanted to see , how after reverting these commits , I will get correct output. 

Thank You

**Comment by tillkamppeter** [comment] 2024-06-11 20:00
This one should be fixed in libcupsfilters 2.x (and so also in cups-filters 2.x) by the merge of PR #56. Should be easy to backport to 1.x.

**Closed as completed** 2024-12-11 20:26 UTC
Labels: 1.x
