### ISSUE TITLE
jobs sent to remote unshared printer stuck in "held since <date>" with no indication of authorization problem

### ISSUE THREAD

**Issue by archenemies** [OpenPrinting/cups-filters#61] opened 2018-09-14 08:09 UTC
(I thought I had submitted this issue but I don't see it in your list; apologies if it shows up twice)

I just upgraded cups and cups-filters on my laptop and on my desktop. The desktop has a printer attached to it. Prior to the upgrade, I was able to print from laptop to the desktop via a local print queue. Now when I try to print, I see in the web interface that the job is listed with "held since \<date\>". When I click the "Release job" button, the page reloads but the job is still "held since"...

Googling, I see that this "held since" message has existed since 2005:

https://ubuntuforums.org/showthread.php?t=2317549

I'd like some help troubleshooting the problem, which may be related to some recent changes in this software (last month or two?) so that my printer can work again.

However, I also think there is a "discoverability" bug here. I never asked for a job to be "held", I'm getting an error message which not only doesn't point to the source of the problem (a log file? something from the STDERR of some failed command?) but also doesn't even appear to be an error message. It leaves me with no clue how to proceed.

I'm attaching an archive with the files that I think may be relevant: local-cupsd.conf local-error_log local-ppd-B210a_Remote.ppd local-printers.conf remote-cupsd.conf remote-error_log remote-ppd-HP_Photosmart_Plus_B210_series.ppd remote-printers.conf

[cups-held-since-bug.zip](https://github.com/OpenPrinting/cups-filters/files/2382188/cups-held-since-bug.zip)

It may be of note that after trying many of the options for remote printing (and finding them all broken for me), I finally stumbled upon a piece of documentation suggesting I run something like this:

    lpadmin -p B210a_Remote -E -v ipp://nameofmydesktop/printers/HP_Photosmart_Plus_B210_series -m everywhere

That was after I created B210a_Remote via the web interface; it succeeded in making the queue work for me (for a couple of weeks until the recent upgrade).

Thanks in advance.

**Comment by archenemies** [comment] 2018-09-14 10:58
I managed to debug this. What happened was that after the upgrade, I had to change the PPD on the server to use hpcups. For some reason after this modification, the printer was no longer being shared. I discovered this in the error log only after I stopped `cups-browsed.service`, which had been polluting the error log and making it impossible to read (also I had "LogLevel debug" in cupsd.conf which was part of the problem)

    sudo systemctl stop cups-browsed.service;

So the issue I am trying to bring to your attention is that when something like this appears in the server log...

    E [14/Sep/2018:10:37:50 +0000] [Client 3] Returning IPP client-error-not-authorized for Create-Job (ipp://amenhotep:631/printers/HP_Photosmart_Plus_B210_series) from 192.168.1.124.

the information is apparently not being passed to the client in a useful form, at least not in the web interface. (Michael Sweet once hinted that I should be using a different interface, but I'm not sure what that is)

**Comment by debiantriage** [comment] 2018-09-14 14:01
Having the printer attached by USB to a server and using hplip is unnecessary in the second decade of the 21st century. Get it on the network with wireless and have it advertise itself with Bonjour.

You are using CUPS/2.2.8 on the server; I assume the client has this version too. Without cups-browsed running, do 'lpstat -e' on the client. The printer should be visible in the output. Print to it with 'lp -d <printer> <file>'. Start cups-browsed and repeat.

Regards,

Brian.

**Comment by archenemies** [comment] 2018-09-14 18:18
Thank you Brian! That's very tantalizing data. Here's what I get:

    $ lpstat -e
    B210a_Remote  
    Brother_DCP-7065DN
    HP_Photosmart_Plus_B210_series_amenhotep
    HP_Photosmart_Plus_B210_series_USB
    Virtual_PDF_Printer
    # sometimes this
    $ lp -d HP_Photosmart_Plus_B210_series_amenhotep mozilla.pdf -o page-ranges=1
    lp: The printer or class does not exist.
    ...
    # or sometimes this
    $ lp -d HP_Photosmart_Plus_B210_series_amenhotep mozilla.pdf -o page-ranges=1
    lp: Destination "HP_Photosmart_Plus_B210_series_amenhotep" is not accepting jobs.

    $ sudo less /var/log/cups/error_log
    ...
    E [14/Sep/2018:11:09:24 -0700] HP_Photosmart_Plus_B210_series_amenhotep: Unable to connect to amenhotep.local:631: Name or service not known

As it happens my printer has wireless, but not wired ethernet. I prefer wires to wireless for various reasons, so that's why I did it this way.

I notice that if I Google "cups how to share printer", then ArchWiki comes up before cups.org, neither of which mention `lpstat -e` or even `lpstat`. But this is a good situation because it means that I can update the wiki with this information and then maybe the next user will find it and not bug you.

When doing the above experiments I also tried turning on `systemd-resolved.service`. It is needed to get Bonjour/LLMNR/mDNS working, I had disabled it because it caused local DNS to be turned off by default (and this broke various stuff).

**Comment by tillkamppeter** [comment] 2018-09-14 19:03
Driverless printing also works via USB, using ippusbxd:
https://github.com/OpenPrinting/ippusbxd

**Comment by tillkamppeter** [comment] 2018-09-14 19:05
Also note that a remote printer must be shared to be able to print on it.

**Comment by archenemies** [comment] 2018-09-14 22:42
Thank you, yes the original problem was lack of sharing.

Is there something we can do to make the GUI "held since" message more informative?

Can you comment on the "Unable to connect to amenhotep.local" error I got, why is CUPS appending ".local" to the name of my server and how do I either fix this or get my computer to resolve it correctly?

**Comment by tillkamppeter** [comment] 2018-09-28 16:09
The CUPS client reporting "held since ..." when trying to a remote CUPS printer which is not shared is caused by CUPS, not by cups-filters, so it is a CUPS issue.

**Comment by archenemies** [comment] 2018-09-28 20:31
OK, I think this is probably not something Apple is going to change/fix since there is a more common similar problem: you get "Filter failed" when there is an error in a filter, instead of a more informative error message which could sometimes be found in /var/log/cups/error_log. And that issue has been closed.

https://github.com/apple/cups/issues/4823

**Comment by tillkamppeter** [comment] 2019-03-16 19:53
We cannot do anything more here. Closing ...

**Closed by tillkamppeter** 2019-03-16 19:53 UTC
