### ISSUE TITLE
This slightly broken PDF file doesn't print with fitplot, prints without it

### ISSUE THREAD

**Issue by akorobkin** [OpenPrinting/cups-filters#6] opened 2017-11-15 17:56 UTC
QPDF project recently released version 7.0.0, fixing the issue https://github.com/qpdf/qpdf/issues/106
I compiled fresh cups-filters with qpdf 7.0.0 and it can print many more files now. 

However, here is a curious problem with this file: [shineline.pdf](https://github.com/qpdf/qpdf/files/1475753/shineline.pdf) 

It prints ok if sent to print untouched: "lp shineline.pdf". At the same time, it doesn't print and produces blank pages if printed as lp -o fit-to-page shineline.pdf. 

Looks like pdftopdf is performing some scaling on it, and that scaling breaks the file. 

Unscaled file has this many errors in error_log:
```
/var/spool/cups/d00035-001 (file position 56627): error decoding stream data for object 29 0: stream inflate: inflate: data: incorrect data check
/var/spool/cups/d00035-001 (file position 56627): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00035-001 (file position 56627): stream will be re-processed without filtering to avoid data loss", current level=WARN
/var/spool/cups/d00035-001 (file position 64303): error decoding stream data for object 30 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00035-001 (file position 64303): error decoding stream data for object 30 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00035-001 (file position 64303): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00035-001 (file position 64303): stream will be re-processed without filtering to avoid data loss", current level=WARN
/var/spool/cups/d00035-001 (file position 67427): error decoding stream data for object 31 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00035-001 (file position 67427): error decoding stream data for object 31 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00035-001 (file position 67427): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00035-001 (file position 67427): stream will be re-processed without filtering to avoid data loss", current level=WARN
PID 21403 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
```

Scaled file has twice more, and they start much earlier than 56627:

```
/var/spool/cups/d00036-001 (file position 238): error decoding stream data for object 4 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 238): error decoding stream data for object 4 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 2855): error decoding stream data for object 8 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 2855): error decoding stream data for object 8 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 7006): error decoding stream data for object 10 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 7006): error decoding stream data for object 10 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 10485): error decoding stream data for object 12 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 10485): error decoding stream data for object 12 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 14385): error decoding stream data for object 14 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 14385): error decoding stream data for object 14 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 18729): error decoding stream data for object 16 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 18729): error decoding stream data for object 16 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 56627): error decoding stream data for object 29 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 56627): error decoding stream data for object 29 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 56627): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 56627): stream will be re-processed without filtering to avoid data loss", current level=WARN
/var/spool/cups/d00036-001 (file position 64303): error decoding stream data for object 30 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 64303): error decoding stream data for object 30 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 64303): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 64303): stream will be re-processed without filtering to avoid data loss", current level=WARN
/var/spool/cups/d00036-001 (file position 67427): error decoding stream data for object 31 0: stream inflate: inflate: data: incorrect data check
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 67427): error decoding stream data for object 31 0: stream inflate: inflate: data: incorrect data check", current level=WARN
/var/spool/cups/d00036-001 (file position 67427): stream will be re-processed without filtering to avoid data loss
Set job-printer-state-message to "/var/spool/cups/d00036-001 (file position 67427): stream will be re-processed without filtering to avoid data loss", current level=WARN
PID 21827 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
```

Is this fixable, what do you think?

**Comment by tillkamppeter** [comment] 2018-02-28 18:13
Can be a QPDF issue. @jberkenbilt can you have a look?

**Comment by jberkenbilt** [comment] 2018-03-02 02:00
What is happening is that qpdf is, as indicated by the messages, failing to uncompress the contents, so it's retrying without doing so. For the case of just having qpdf do something, this would be innocuous. A quick perusal of the cups-filters code reveals that there are some places in the code where replaceStreamData is being called with a string. I can't specifically find the code, but if cups-filters is attempting to include the original contents as part of the string and is doing this in a way that will catch and ignore exceptions, it's quite possible that it could be losing page contents whenever qpdf can't decode the pages. As an alternative, it would be possible to call addPageContents to add something before and again to add something after the original stream, which would make it irrelevant whether the contents could be decoded. I also see code that does this, so I can't say for sure whether this is happening. Bottom line on this: it's possible that cups-filters is somehow trying to retrieve the actual contents and doing so in a way that causes them to be discarded in the event of decoding problems.

The second question is why is qpdf not able to decode these streams when other things can. For this, I'll open a qpdf bug and keep a copy of the file. There may be some small change I can make to the deflate filter to make it handle these streams. I can open the file with evince, so clearly it is possible to decode them.

**Comment by jberkenbilt** [comment] 2018-03-02 02:07
So, just to be clear, there may be a qpdf bug here, which I will investigate, but there also may be a way to fix cups-filters so it would be able to successfully handle the file in spite of the problem. If it is detected during a study of cups-filters's that qpdf is somehow throwing the data away on its own, that would definitely a bug, but I rather doubt that is happening. But if it is, another bug report against qpdf should be created.

**Comment by tillkamppeter** [comment] 2018-03-02 22:39
@smilingthax, as you have done the QPDF-based pdftopdf, can you have a look into this and check whether there are any ways to address this in pdftopdf? Thanks.

**Comment by smilingthax** [comment] 2018-03-03 12:13
Well, pdftopdf has basically two modes (as did pstops): For trivial transformations (add border, ...), it uses addPageContents. For everything else (number-up, ...) it transforms a page into an xobject by concatenating all the streams in a given page's /Contents and creating a wholly new stream, with completely different stream dictionary [1]. This form xobject can now be drawn with arbitrary rotation, etc. onto a (new) blank page (and also additional ones, cf. number-up). 

Finally, pdftopdf contains no fast-path for fitplot, so it uses the non-trivial transformation mode (which has to be used for number-up>1, etc. anyway).

<br>
[1] In qpdf_xobject.cc:

```
  std::vector<QPDFObjectHandle> contents=page.getPageContents();

  auto ph=PointerHolder<QPDFObjectHandle::StreamDataProvider>(new CombineFromContents_Provider(contents));
  ret.replaceStreamData(ph,filter,decode_parms);
```
`CombineFromContents_Provider` is basically the same as QPDF 8.0's new (private) `CoalesceProvider`, with `ret` being the new xobject stream.

**Comment by jberkenbilt** [comment] 2018-03-03 16:40
I just pushed a fix to qpdf to ignore checksum errors when uncompressing streams. I see that other PDF readers do this, and it makes sense. Combining this with slightly different options to zlib's inflate method enables qpdf to successfully uncompress these streams. Do you think it's worth release 8.0.1 with just this fix? Would it make it into Ubuntu 18.04 since it's a small bug fix and 8.0.0 is "proposed" and was in debian prior to the feature freeze?

**Comment by jberkenbilt** [comment] 2018-03-03 17:02
I should have explicitly stated that qpdf, with the fix, is able to handle this file with no errors, warnings, or loss of data. Thanks for alerting me to this issue.

**Comment by tillkamppeter** [comment] 2018-03-03 17:39
@jberkenbilt, thanks for the quick fix.
Unfortunately, I doid not sync QPDF 8.0.x into Ubuntu 18.04 before Feature Freeze as the cups-filters changes needing the new features of QPDF 8.0.x had not made it into 18.04.
So I want to ask you whether the fix is independent of the new 8.0.x features of QPDF and the patch can also be applied to 7.1.1 (the version currently in Ubuntu 18.04). Is this possible?

**Comment by jberkenbilt** [comment] 2018-03-03 19:51
The code change will apply to 7.1.1 and should still resolve this problem. It is a very localized fix, and it touches a a file I did not change at all between 7.1.1 and 8.0.0. The test suite change will not apply cleanly, but it would be trivial to fix. The only change to the test suite was that the case that was previously exercising the reporting of the zlib data check error now no longer does so. It would be fine with me if you apply this as a patch to qpdf 7.1.1 in Ubuntu. I'm not going to release 7.1.2 or do anything with the debian packages since 8.0.0 is already in. I will probably release 8.0.1, but I'll let 8.0.0 bake in a little first. I'll attach a patch relative to 7.1.1 to this bug report in a couple of minutes.

**Comment by jberkenbilt** [comment] 2018-03-03 19:58
Here's a patch (-p0) relative to 7.1.1 that fixes this problem.

```patch
--- libqpdf/Pl_Flate.cc.orig	2018-02-04 18:31:42.000000000 -0500
+++ libqpdf/Pl_Flate.cc	2018-03-03 14:53:38.769727153 -0500
@@ -1,5 +1,6 @@
 #include <qpdf/Pl_Flate.hh>
 #include <zlib.h>
+#include <string.h>
 
 #include <qpdf/QUtil.hh>
 
@@ -71,7 +72,8 @@
     while (bytes_left > 0)
     {
 	size_t bytes = (bytes_left >= max_bytes ? max_bytes : bytes_left);
-        handleData(buf, bytes, Z_NO_FLUSH);
+        handleData(buf, bytes,
+                   (action == a_inflate ? Z_SYNC_FLUSH : Z_NO_FLUSH));
 	bytes_left -= bytes;
         buf += bytes;
     }
@@ -125,6 +127,14 @@
 	{
 	    err = inflate(&zstream, flush);
 	}
+        if ((action == a_inflate) && (err != Z_OK) && zstream.msg &&
+            (strcmp(zstream.msg, "incorrect data check") == 0))
+        {
+            // Other PDF readers ignore this specific error. Combining
+            // this with Z_SYNC_FLUSH enables qpdf to handle some
+            // broken zlib streams without losing data.
+            err = Z_STREAM_END;
+        }
 	switch (err)
 	{
 	  case Z_BUF_ERROR:
--- qpdf/qtest/qpdf/issue-106.out.orig	2018-03-03 14:53:38.769727153 -0500
+++ qpdf/qtest/qpdf/issue-106.out	2018-03-03 14:54:16.785908314 -0500
@@ -1,6 +1,4 @@
 WARNING: issue-106.pdf: file is damaged
 WARNING: issue-106.pdf (file position 809): xref not found
 WARNING: issue-106.pdf: Attempting to reconstruct cross-reference table
-WARNING: issue-106.pdf (file position 965): error decoding stream data for object 8 0: stream inflate: inflate: data: incorrect data check
-WARNING: issue-106.pdf (file position 965): stream will be re-processed without filtering to avoid data loss
 qpdf: operation succeeded with warnings; resulting file may have some problems
```

**Comment by tillkamppeter** [comment] 2018-03-03 22:05
Thank you very much. I will apply this patch to the QPDF package of Ubuntu 18.04.

**Comment by jberkenbilt** [comment] 2018-03-04 13:59
I've gone ahead and done a 8.0.1 release that includes this fix and one other small, command-line-only enhancement.

**Comment by tillkamppeter** [comment] 2018-03-06 16:16
QPDF 8.0.1 synced now. 8.0.2 will be synced as soon as it gets available.

**Comment by akorobkin** [comment] 2018-03-06 16:20
Thank you guys for resolving this curious issue. I can confirm that the patch works with 7.1.1.

**Comment by jberkenbilt** [comment] 2018-06-18 14:42
Is this issue resolved? Is there anything else I have to do here? I don't think there is, so I'm taking this off my list unless I hear otherwise. Thanks.

**Comment by tillkamppeter** [comment] 2018-06-18 16:24
The problem is solved, as we got confirmation from the OP. Closing ...

**Closed by tillkamppeter** 2018-06-18 16:24 UTC
