### ISSUE TITLE
No printing and "Failed filter" error after upgrading from version 1.20.4 to 1.21.0

### ISSUE THREAD

**Issue by erikwesselius** [OpenPrinting/cups-filters#57] opened 2018-08-24 19:36 UTC
Description:

After a full system update (on an Arch Linux system), my Kyocera FS-1000 printer no longer receives any print jobs.

Cups reports the error message "Failed filter".

In the systemd logs I found this:
ANOM_ABEND auid=4294967295 uid=209 gid=209 ses=4294967295 pid=2597 comm="foomatic-rip" exe="/usr/lib/cups/filter/foomatic-rip" sig=11 res=1

The file foomatic-rip belongs to the package cups-filters and that package was indeed updated today (to version 1.21.0-1). After downgrading cups-filters to the previous version (1.20.4-2) the printer is responding normally again.

The issue was confirmed by another user with another printer (Brother HL-2240D).

See [my original bug report](https://bugs.archlinux.org/task/59775) on the Arch Linux bugtracker.

**Comment by PetriKaukasoina** [comment] 2018-08-25 15:53
Remove free(newvalue) in line 1047 of options.c

**Comment by tillkamppeter** [comment] 2018-08-25 17:40
Thank you very much.

I have now fixed it a little bit differently and pushed it to the GIT (commit 98b2b528). Can you test this version? Thanks.

**Comment by tillkamppeter** [comment] 2018-08-25 17:42
This bug was caused by the Coverity fixes in pull request #53.

**Comment by PetriKaukasoina** [comment] 2018-08-25 18:12
Works here, thanks.

**Comment by tillkamppeter** [comment] 2018-08-25 19:34
Thank you very much for testing.

**Closed by tillkamppeter** 2018-08-25 19:34 UTC

**Comment by tillkamppeter** [comment] 2018-08-26 09:52
I have released 1.21.1 with the fix included now.
