### ISSUE TITLE
Why doesn't `driverless` copy remote PPD options?

### ISSUE THREAD

**Issue by lbschenkel** [OpenPrinting/cups-filters#228] opened 2020-05-03 18:08 UTC
*I realize that perhaps this is not the best forum for this question, but I [tried the mailing list](https://lists.linuxfoundation.org/pipermail/printing-architecture/2020/003799.html) and given past activity there, I'm not sure if there is the right place for this kind of question either.*

I have read https://wiki.debian.org/CUPSDriverlessPrinting and surrounding wiki pages. I think I've managed to get a good grasp about how a modern CUPS setup should work, and the differences between CUPS' `everywhere` and cups-filters' `driverless` PPD generators.

I'm still confused about a particular detail, though.

I have an old printer (meaning: not supporting AirPrint or IPP everywhere) locally connected to a CUPS server (2.2.10). I use the Gutenprint printer drivers. The shared CUPS queue supports all the types necessary for a `everywhere` or `driverless` setup in clients. My desktop computer is running `cups-browsed` (1.27.4-1) which auto-setups a queue using `drvless.ppd`. I can print through it. So far so good.

However, what I don't understand is why aren't the PPD options available in the server (the ones exposed by Gutenprint, and very comprehensive) copied over and available in my local queue? I only see generic (and fewer) options for paper size, resolution, etc. When using macOS as a client I noticed that it does copy the server options in the client PPD, which is great. So I am wondering why `driverless` does not do the same? Is this a deliberate design decision? Or is my set-up broken somehow?

This current behaviour decreases the usefulness of `cups-browsed` quite a lot, because if I need to control those non-exposed options I'm forced to print directly to the remote queue via a print dialog that does discovery.

**Comment by NJRoadfan** [comment] 2020-08-12 19:06
I just tested this with the following:

*Linux CUPS 2.3.3 server running latest cups-filters release 1.27.5 with a hp color LaserJet 3700dn setup with HP's OEM PPD.
*macOS catalina client (CUPS 2.3.1)
*Linux CUPS 2.3.3 client running latest cups-filters release 1.27.5

The macOS client pulled the PPD settings as expected. Going into the CUPS web interface on macOS and adding printer has the same result. IPP-Everywhere was available as a driver option in the web interface, but Apple hides this on the native System Preferences pane.

The Linux client too worked as expected. Automatically detected and added printer queues on the CUPS server and pulled all the advanced PPD settings (duplexing on/off, paper sizes, etc.). I checked the generated PPD and the client is using `drvless.ppd`.

Of note, cups-filters on the Linux client also detected the printer itself and automatically added a queue for it. The printer has a HP JetDirect 635N card in it that supports IPP 1.0 and Bonjour, but too old for IPP-Everywhere/Airprint. CUPS automatically added the queue and the generated PPD specifies the input language as PCL, Postscript, or PDF. Advanced settings were NOT available in this case and the default output resolution was set to 300dpi (printer can do 600dpi). The PPD also had a note in it that the printer didn't respond to IPP media size queries.

On macOS, if I directly added the printer itself, Apple pulls driver software from hp, which includes stuff like a proper picture of the printer for the queue's icon. Advanced options and querying of supply levels (toner and fuser life) is supported. Supply levels did not work via the CUPS queues.

**Comment by tillkamppeter** [comment] 2020-08-12 19:31
The IPP Everywhere/IPP driverless protocol cannot convey arbitrary options, only options which can be represented by standard IPP attributes. Gutenprint has a huge range of options and many are actually not representable as IPP options and so do not get visible to the client. In contrary the options of most typical PostScript laser printers have their IPP equivalents and so make it to the client via IPP, this is why @NJRoadfan is more successful with his client PPD files.
@NJRoadfan note that due to the fact that your printer is only IPP 1.0 which means pre-driverless-era you get only a very rudimentary PPD when trying to set up your printer as driverless IPP printer. This is also most probably the reason why CUPS cannot poll toner levels from it but a proprietary MacOS driver can.
All this is expected behavior, no bug of cups-filters. Therefore I will close this issue here.
Note also that Gutenprint will soon be moved to the new printer driver format, the Printer Application. This is an emulation of a driverless IPP printer on the local machine, which makes CUPS and `cups-browsed` set up a print queue fully automatically. The developers of Gutenprint will also find a way for the user to access the vast amount of adjustment parameters.

**Closed by tillkamppeter** 2020-08-12 19:31 UTC

**Comment by lbschenkel** [comment] 2020-08-13 05:04
@tillkamppeter Thanks for the response. I'm aware of the direction of moving into "Printer Applications" instead of printer drivers and PPDs, but I'm guessing that it's still months/years away from being available in practice (packaged in mainstream distros)?

If you don't mind, could you tell me if there's any manual way in which I can set up a local printer queue connected to the remote printer queue that has all the options from the remote queue, but *without* installing Gutenprint locally and sending "raw" to the server? Basically I just want to use the everywhere/driverless model, and *also* be able to controll all the options in the client. I understand that this is not possible by default (even though macOS seems do to it), but is there a way I can "force" it, even if I need to copy PPDs around?
