### ISSUE TITLE
rotating a page to landscape orientation offsets the image

### ISSUE THREAD

**Issue by dtorop** [OpenPrinting/cups-filters#456] opened 2022-03-30 04:46 UTC
When a landscape orientation PDF passes through pdftopdf with option `landscape=true`, the resulting image is offset. Removing the `landscape=true` option does the right thing (auto-rotating the image without offsetting it).

This is a change in behavior between cups-filters v1.28.7 or 1.28.12. I have not tested 1.28.13, and don't know if this is the same bug as #454 and is therefore now fixed.

As a test, use this PDF generated by darktable: 
[dt-landscape-test.pdf](https://github.com/OpenPrinting/cups-filters/files/8377035/dt-landscape-test.pdf)

Running `/usr/sbin/cupsfilter -p /etc/cups/ppd/PDF.ppd -o landscape=true -m application/vnd.cups-pdf dt-landscape-test.pdf > dt-landscape-test-filtered-with-landscape-option.pdf` produces this (offset) file:
[dt-landscape-test-filtered-with-landscape-option.pdf](https://github.com/OpenPrinting/cups-filters/files/8377042/dt-landscape-test-filtered-with-landscape-option.pdf)

Running `/usr/sbin/cupsfilter -p /etc/cups/ppd/PDF.ppd -m application/vnd.cups-pdf dt-landscape-test.pdf > dt-landscape-test-filtered-without-landscape-option.pdf` produces this (correctly autorotated) file:
[dt-landscape-test-filtered-without-landscape-option.pdf](https://github.com/OpenPrinting/cups-filters/files/8377047/dt-landscape-test-filtered-without-landscape-option.pdf)

While the right call may be to simply not set `landscape=true`, this does appear to be a regression which resulted in this darktable bug https://github.com/darktable-org/darktable/issues/11416.

Note that it is not necessary to use a darktable generated PDF. For example, this PDF creating with LibreOffice produces the same behavior:
[print orientation test landscape.pdf](https://github.com/OpenPrinting/cups-filters/files/8377053/print.orientation.test.landscape.pdf)

**Comment by tillkamppeter** [comment] 2022-03-30 09:22
First, if a user application, like Darktable prints a file, it should not use the "landscape" option. If the page is actually landscape (width > height) the `pdftopdf` filter automatically rotates the page by 90 degrees in case the printer pulls in the paper short-edge-first (portrait orientation, size in PPD has width < height) and does not rotate the page if the printer pulls in the paper long-edge-first (landscape orientation, size in PPD has width > height). Other applications neither use `landscape` nor `orientation-requested` options/attributes, especially if they send PDF files.

For my understanding, "landscape" is more for plain text files to arrange the text in a landscape format.

My suggestion to solve the problem is to remove the line which adds the "landscape" option from the Darktable code. As you have already tried to solve it by adding a line to add the "fit-to-page" option, I suggest you to not add "fit-to-page" but remove the line which adds "landscape" from the Darktable code. Now all files should print correctly right away.

What "landscape" should do in the `pdftopdf` filter to do something useful I have to find out at first. I never put a lot of thought into this option as the automatic page management of `pdftopdf` simply does the right thing without the option, and up to now I did not hear of any user application which supplies the "landscape" option with landscape-shaped documents.

Simply turning the document by 90 degrees, as [the CUPS documentation](https://openprinting.github.io/cups/doc/options.html)  suggests would also be wrong, at least if one rotates after the automatic page management got applied. Another possibility for it would be overriding the automatic page management, letting `pdftopdf` not do any automatic rotation and then rotate according to the supplied "landscape" or "orientation-requested" option.

@michaelrsweet what is a filter like the `pdftopdf` filter supposed to actually do if the user supplies the "landscape" or "orientation-requested" option?

**Comment by michaelrsweet** [comment] 2022-03-30 14:17
@tillkamppeter In the case of the pdftopdf filter, it shouldn't do anything with it since the orientation is passed through to the printer. For a raster filter, it should honor the request, rotating as necessary to produce the IPP-defined orientation (landscape is counter-clockwise, reverse-landscape is clockwise) based on the orientation of the input paper (typically portrait for short-edge feed and landscape or reverse-landscape for long-edge feed)...

**Comment by dtorop** [comment] 2022-03-30 14:18
> My suggestion to solve the problem is to remove the line which adds the "landscape" option from the Darktable code.

@tillkamppeter Yes, that sounds right to me as well. I wrote darktable-org/darktable/pull/11430 with that change. This certainly makes things much more straightforward on the darktable side. Thank you for the detailed explanation!

> The Debian wiki has [this page](https://wiki.debian.org/CUPSPdfToPdf).

@debiantriage That page is helpful!

A [query](https://github.com/darktable-org/darktable/pull/11430#issuecomment-1082698918) from the darktable side:

> I don't have objection on relying to rotation being done by the driver but pdf2pdf is only one driver amongst many.

So long as darktable relies on CUPS for output, we can expect that any modern system will have the pdf2pdf filter installed with the autorotate function enabled?

**Comment by dtorop** [comment] 2022-03-30 14:34
Given https://github.com/darktable-org/darktable/issues/11416#issuecomment-1082726205 (`Upgrade: cups-filters:amd64 (1.28.11-2, 1.28.12-1)`), it looks like the landscape behavior changed in v.1.28.12.

**Comment by debiantriage** [comment] 2022-03-30 14:37
@tillkamppeter I observe the described behaviour with cups-filters 1.28.12 (Debian unstable) but not with 1.28.7 (Debian stable) or 1.21.6 (buster).

**Comment by tillkamppeter** [comment] 2022-03-30 19:50
> Given [darktable-org/darktable#11416 (comment)](https://github.com/darktable-org/darktable/issues/11416#issuecomment-1082726205) (`Upgrade: cups-filters:amd64 (1.28.11-2, 1.28.12-1)`), it looks like the landscape behavior changed in v.1.28.12.

@dtorop I did several bug fixes on `pdftopdf` recently, mainly to make N-up working with all settings of `print-scaling` and to get correct centering even if the unprintable margins of the printer are not symmetric. As with auto-rotation no one needs (and so no one uses) the "landscape" option I forgot about it completely and did not test with it.

We need a test suite for cups-filters (topic for next Linux Plumbers Conference).

**Comment by tillkamppeter** [comment] 2022-03-30 19:57
@debiantriage your documentation is great, I have learned a lot about `pdftopdf` which I did not know before. I did not write it by myself. It is done by many contributors, not only by Tobias Hoffmann and me. There were many people who have helped to get the PDF workflow coded.

@debiantriage we should somehow upstreamize (move to OpenPrinting) your documentation.

**Comment by dtorop** [comment] 2022-03-30 20:34
@tillkamppeter Yes good news about the fix in darktable. As Pascal wrote, authoritative upstream advice most welcome. And good to take the rotation work out of darktable print code.

And yes, that makes sense about plumbing and test suite. I'll keep this issue open, fwiw...

**Comment by debiantriage** [comment] 2022-04-03 11:02
@tillkamppeter For a PDF with mixed orientation pages ` pdfinfo -f 1 -l 3 mixed.pdf` shows

> Page    1 size: 595 x 842 pts (A4)
Page    1 rot:  0
Page    2 size: 841.89 x 595.28 pts (A4)
Page    2 rot:  0
Page    3 size: 595 x 842 pts (A4)
Page    3 rot:  90

Pages 2 and 3 are PDF landscape pages.

After treatment by pdftopdf on cups-filters 1.28.7 and earlier, out.pdf is

> Page    1 size: 595 x 842 pts (A4)
Page    1 rot:  0
Page    2 size: 841.89 x 595.28 pts (A4)
Page    2 rot:  270
Page    3 size: 595 x 842 pts (A4)
Page    3 rot:  0

Autorotation has taken place by rotating the **whole** of PDF pages 2 and 3.

On cups-filters 1.28.13 out.pdf shows

> Page    1 size:  595 x 842 pts (A4)
Page    1 rot:   0
Page    2 size:  595 x 842 pts (A4)
Page    2 rot:   0
Page    3 size:  595 x 842 pts (A4)
Page    3 rot:   0

Autorotation still takes place but it seems to me that PDF pages 2 and 3 have been redesigned (rather than the whole page rotated) to have the **text rotated** to put  it parallel to the long edgeof a PDF portrait page. I am curious why pdftopdf's technique has changed.

The command to use pdftopdf is

```
/usr/sbin/cupsfilter -p test.ppd -m application/vnd.cups-pdf  mixed.pdf > out.pdf
```
mixed.pdf and test.ppd are attached.

[mixed.pdf](https://github.com/OpenPrinting/cups-filters/files/8404288/mixed.pdf)
[test.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/8404304/test.ppd.txt)

**Comment by tillkamppeter** [comment] 2022-04-03 17:50
Fixed in commit 9b86754.

@dtorop Thanks a lot for the bug report.

@debiantriage @michaelrsweet Thanks a lot for all the help and for your great documentation.

**Closed by tillkamppeter** 2022-04-03 17:50 UTC

**Comment by tillkamppeter** [comment] 2022-04-03 22:24
Now also the output when not using auto-rotating (`-o nopdfAutoRotate`) and controlling fully manually by `orientation-requested` and `landscape` is correct.

Fixed this with commit f730a1f8c2.

**Comment by tillkamppeter** [comment] 2022-04-04 10:47
Backported the fix to the 1.x branch as commit 161b32b134097.

**Comment by tillkamppeter** [comment] 2022-04-04 11:10
[cups-filters 1.28.14](https://github.com/OpenPrinting/cups-filters/releases/tag/1.28.14) released with the fix included.

**Comment by jsmeix** [comment] 2022-04-08 08:17
@tillkamppeter 
I have a question regarding what you wrote above in
https://github.com/OpenPrinting/cups-filters/issues/456#issuecomment-1082832984
```
If the page is actually landscape (width > height)
the pdftopdf filter automatically rotates the page by 90 degrees
in case the printer pulls in the paper short-edge-first
(portrait orientation, size in PPD has width < height)
and does not rotate the page if the printer pulls in the paper
long-edge-first (landscape orientation, size in PPD has width > height).
```

I do not understand why it matters if the printer pulls in the paper
short-edge-first or long-edge-first.

There are printers that normally pull A4 (or Letter) paper long-edge-first
also for usual portrait printing content (printing content width < height).

In particular A3 capable printers pull A4 long-edge-first for faster A4 printing speed.
They pull A3 short-edge-first because their printing unit is A3 short-edge wide.
This means they can pull A4 long-edge-first to use the whole width of the
printing unit also for A4 printing so the time for a A4 long-edge-first paper
to pass the printing unit is the time for the A4 short-edge length
which is only 71% compared to the A4 long-edge length
so pulling A4 long-edge-first makes A4 printing 40% faster.

**Comment by tillkamppeter** [comment] 2022-04-08 10:48
When I say "the printer pull the paper short-edge first" its some simplified description. I mean that the raster output data should be arranged in lines of pixels parallel to the short edge. Imagine an A4 sheet, and to describe the graphics on it a bitmap, as series of bits (not a matrix of bits) is created. For this one goes line by line (like with text) over the page. There are two possibilities, to have the lines parallel to the long edge (if you imagine the page in landscape orientation) or parallel to the short edge (portrait).

For high-end laser printers which print on A3 this does not matter. They have enough space for the raster data of a full page, so if a job contains raster data with the bitmap lines parallel to the short edge and the printer pulls A4 paper long-edge-first it is no problem, as it only starts printing after having received the full page.

But for cheaper printers the arrangement of raster data is important as they cannot hold the full page. They receive a certain band of bitmap data and print it out before they receive the next band. So the bitmap has to be arranged in the correct direction now. If the printer pulls the page short-edge-first (the standard for these cheaper printers) the bitmap lines have to be parallel to the short edge of the paper. The CUPS/PWG/Apple Raster file which Ghostscript produces in the `gstoraster` filter step displays in portrait orientation in `rasterview`, and if the content is landscape-oriented, you see it rotated by 90 degrees, the rotation being performed in the `pdftopdf` filter step. This is the situation which I call short-edge-first, even if it does not necessarily correspond with the actual printer hardware. The `rasterto...` CUPS driver filter or the driverless PWG/Apple-Raster consuming printer receives and consumes the bitmap line by line, beginning from what you see at the top in `rasterview`.

The DesignJet printer of issue #457 is probably not a cheap printer, but it also cannot hold the raster data of a full page, due to its large page sizes. It also has a roll feeder and a cutter so that you can easily produce any custom page size with the width of the roll and arbitrary (only less than the length remaining on the roll) in the other dimension. To save paper you decide for each job whether you want to print it long-edge-first or short-edge-first, and as the printer cannot hold the raster data of the full page, landscape-oriented output (raster lines parallel to long edge) need to get produced.

You actually do not need to specify the "landscape" option on this kind of printer, it is enough to specify the custom page size in landscape orientation (`Custom.42x20in`) or select a landscape variant of your page size from the PPD file (`A3.Transverse`) and `pdftopdf` rotates a portrait-oriented input page automatically then.

**Comment by jsmeix** [comment] 2022-04-08 11:25
I think one can leave out the paper handling in the printer
(because this is a printer internal "implementation detail")
and one should leave out the word "landscape" in printing issues
because using it only causes endless confusion because
```
There is no such thing as "landscape printing"
```

I described my understanding in
https://en.opensuse.org/SDB:Landscape_Printing
some time ago based on traditional printing with drivers and PPD files.

As fas as I understand it all what matters is that the printing content
is within the printable area of the selected page size for the print job
(regardless if the content is provided as PostScript or as raster data).

**Comment by michaelrsweet** [comment] 2022-04-08 12:56
@jsmeix Short version: the media orientation generally only matters for (PWG or Apple) raster printing and when printing envelopes (to make sure the flap is on the top). For PDF, PostScript, and JPEG the printer will handle rotating as needed...

Long version: early AirPrint printers that were able to pull media by the long edge did not run at full speed because they needed to buffer the whole page (to rotate it) before printing. The PWG defined new IPP member attributes for media-col-ready and media-col-database to allow a client to detect the orientation of the media in the tray and do the raster rotation on the client in order to print at full speed. These additions also provide some guidance for media that is orientation-dependent such as envelopes and letterhead (where rotating the page content the wrong way would yield incorrect printed results...)

**Comment by jsmeix** [comment] 2022-04-08 13:03
@michaelrsweet 
thank you for your explanation!

It shows again that "landsape" issues are complicated.
