### ISSUE TITLE
Peripage A6

### ISSUE THREAD

**Issue by KataPi** [OpenPrinting/cups-filters#268] opened 2020-07-24 08:25 UTC
Hello, I need help.
How to use this thermal printer?
Peripage A6 on ubuntu or raspberry
(203 dpi - bluetooth and usb)
cups recognizes the name but asks which driver to use

Windows has the manufacturer's driver:
http://m.ileadtek.com/appdownload
Raspberry via bluetooth does not find services ...
on raspberry I installed cups,
cups-filters and foomatic (engine and db) but it doesn't work.
on Android (on the phone) it works great.
Manufacturer's app (http://m.ileadtek.com/appdownload) and not:
https://play.google.com/store/apps/details?id=ru.a402d.peripage.free&hl=it
https://play.google.com/store/apps/details?id=com.noble.activity.printerperipage&hl=it
I also emulated Android on Ubuntu (Anbox) but no bluetooth support and I couldn't find the printer.

I believe it doesn't work with ESC drivers
I asked about apple / cups but they directed me to openprinting filters.

Can this printer be added to the database?
If there are no filters, can someone explain to me how to do it?
Any help is appreciated.
Thank you

**Comment by tillkamppeter** [comment] 2020-08-06 20:08
Unfortunately, there is no way to directly use your printer under Linux, as there actually do not exist drivers. With emulating a supported operating system (like Android via Anbox) you were going the right way. Perhaps you should use USB instead of Bluetooth then.
Most probably it does not support driverless printing, as there is a specialized app for Android to use it.
You could try driverless nevertheless. Install [ipp-usb](https://github.com/OpenPrinting/ipp-usb) and connect your printer via USB. If
```
driverless
```
lists your printer you can use it without specal driver.
I am closing this issue as it is not a bug in cups-filters.
Please tell here whether you finally get it working.

**Closed by tillkamppeter** 2020-08-06 20:08 UTC
