### ISSUE TITLE
cups 2.2.7 causes image on each subsequent page to rise about 0.10 inch on network printer

### ISSUE THREAD

**Issue by jferguson4** [OpenPrinting/cups-filters#261] opened 2020-07-07 15:32 UTC
Please delete this or redirect it if not appropriate here. Or let me know where i should have posted it.  

Printer is Sun SPARCprinter I connected to Sun SPARCstation 10.  Ghostscript 6.01 installed in SunOS 4.1.4 on SPARCstation 10.  Network machine running Cups 2.2.7 under Ubuntu 18.04 is HP Elite.  This system prints flawlessly to HP Envy network printer.

Image rising problem does not occur with any local printing on Sun.  Problem does not occur printing "print-to-pdf"files made on the HP Elite but printed on Sun using lp -Pgp printfile.pdf  (gp is name of Ghostscript print-driver on Sun).

thinking problem was in PPD on elite, I've tried all sorts of variations on PageSize, ImageableArea, and even PaperDimension without fixing problem.  

Does cups have a way to re-index top of page for each page?  Where in the cups code should I be looking for whatever is causing this?

For whatever it is worth, this system worked perfectly up to 2017 - not sure when it got this problem because of a move with Sun system down for about a year.

Has anyone ever seen this problem before?

**Comment by dipanshu231099** [comment] 2020-07-10 15:07
hi @jferguson4 
this is in fact correct place to mention an issue.
i would suggest you to go through following steps
### 1. Using the latest git version
To use the version you can follow the INSTALL instructions to build the git version in your system.

### 2. center-of-pixel method
this is applicable when the Ghostscript is rendering PostScript or PDF files into a raster format:
If you are using a low resolution printer then you can use the ```center-of-pixel```  method.
to use this method you can either
- use it during the time of printing by adding the option as ```-o CenterOfPixel``` or ```-o center-of-pixel```
- set it as default value in the PPD file of your print queue by adding the following lines:
```
*OpenUI *CenterOfPixel/Center Of Pixel: PickOne
*OrderDependency: 20 AnySetup *CenterOfPixel
*DefaultCenterOfPixel: true
*CenterOfPixel true/true: ""
*CenterOfPixel false/false: ""
*CloseUI: *CenterOfPixel
```

### 3. 
if the issue still persists, it would be very helpful if you could send the commands used, and the PPD of the printer, so that we can try to replicate the issue and get greater details.

 Regards.

**Comment by jferguson4** [comment] 2020-07-10 16:03
I can send the PPD as an ascii txt file.  I'll do it if your recommendation doesn't solve the problem.   Or is it possible that Cups is doing something to it that would be revealed using the method you describe above?

Thanks you for responding to this.
john

**Comment by tillkamppeter** [comment] 2020-07-10 21:44
You also use a VERY old Ghostscript version. 6.01 is many years old. Try using the current version, [9.52](http://www.ghostscript.com/). Many bugs have been fixed in all the years.

**Comment by tillkamppeter** [comment] 2020-07-10 21:48
@dipanshu231099, the (3) in your post shows the steps to get the job data which would go to the printer, not the PPD file.
@jferguson4 to attach your queue's PPD file uncompressed get the file
```
/etc/cups/ppd/<name of original queue>.ppd
```
copy it, and rename the copy to have a `.txt` file name extension. Attach this file to this bug report.

**Comment by jferguson4** [comment] 2020-07-10 22:24
It is true that Ghostscriopt is very old. But I'm running it on SunOS4.1.4 (1992).  In order to compile Ghostscriipt  I had to bring up Gnu Compiler 2.95. In order to compile a more recent version of Ghostprint, I needed a newer compiler.  I tried to do it,but there was a nightmare of missing components, and maybe it;s not possible.  Don't know.

I'm sticking with 6.01 because of that.  My guess is if I cannot make the center-pixel filter wotk, I'll go with a spooler to which I write a print-to-file pdf which in turn sends it to the ghostscript printer.

**Comment by dipanshu231099** [comment] 2020-07-11 04:20
@jferguson4 if you wish to stick with the same versions. I request you to also mention the version of cups-filter you are using. Also it would be very helpful if you can send us the required PPD, as mentioned in the above comments

**Comment by jferguson4** [comment] 2020-07-11 15:06
OK, I can see what you are asking for.  I can upgrade cups in my Ubuntu machine to latest, but I think I'm pretty much stuck with Ghostscript 6.01 on the Sun SPARCstation.  Is it possible that a Ghostscript that old will not recognize the centerofpixel option?

I will send the pdd file, and the Ghostscript printing default options set on the Sun.  later today.

**Comment by dipanshu231099** [comment] 2020-07-11 15:19
@jferguson4 did you try centreofpixel method with your current versions. Also if it is not working it may be due to some bug in ghostscript 6.01 as pointed out by @tillkamppeter. 
Anything further can be only said once we are able to succesfully replicate the issue as per your given versions.

**Comment by jferguson4** [comment] 2020-07-11 18:51
Gentlemen,
I shouldn't be wasting your time with this.  It appears that there is no centreofpixel option in the Ghostscript 6.01 files or executable which I have.  I tried searching and could find a reference to center of pixel rule but that was in a note in the Source.

I am probably the only one in the world who is still running a SPARCprinter 1, so unless this issue is interesting to you your time might be better spent on something else.

The ppd below works except for the image climbing.  

[sp1.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4907453/sp1.ppd.txt)

I have some other ppd's which include cups-filter vnd.cups-rater 0 ratertoraster and they also work but with same problem.
One of the ppd's I found on the net included a reference to rastertosparc, but I have been unable to find a copy of it.

Thanks you for looking at this.
john ferguson

**Comment by jferguson4** [comment] 2020-07-11 19:55
Maybe what I should do is build up  a modern ppd which will work with my system.

**Comment by tillkamppeter** [comment] 2020-07-11 22:04
@dipanshu231099, thank you very much for working on this. As here is very old software and one specific, very old printer is involved, we are not able to reproduce this and to provide a fix. Nor would such a fix help many people.
@jferguson4, thank you very much for your bug report. I think that it really is not worth to still put much work in it, due to the old system environment and the old, very specific printer model. So I am closing here. You can still post comments and we get notified, so if you have success later, simply post.

**Closed by tillkamppeter** 2020-07-11 22:04 UTC
