### ISSUE TITLE
gstopdf ignores NumCopies

### ISSUE THREAD

**Issue by ndreisg** [OpenPrinting/cups-filters#87] opened 2019-01-11 08:02 UTC
On my Ubuntu system I have cups-filters version **1.8.3** (still uses pstopdf).
My customer has a newer version which uses **gstopdf** instead of **pstopdf**.

When I print a Postscript file with NumCopies in the header, **pstopdf** is correctly printing multiple copies while **gstopdf** seems to ignore the NumCopies value.

**Comment by ndreisg** [comment] 2019-01-11 08:09
pstopdf seems to use the -dDoNumCopies parameter in the gs command while gstopdf doesn't. Can I configure this somehow?

**Comment by ndreisg** [comment] 2019-01-11 09:44
I now found out which version my customer is using (1.11.6)
I was able to reproduce the issue on my system.
I also tried with a newer version (1.20.4)
I was not able to install the latest version (1.21.X) on Ubuntu 16.04 because it needs QPDF 8.1.0 which is not available on 16.04

**Comment by dheeraj135** [comment] 2019-02-26 18:16
@ndreisg Please try to reproduce this issue on the latest version of cups-filters(1.22.x). You can install QPDF from [source](https://github.com/qpdf/qpdf).

**Comment by yugeshk** [comment] 2019-02-28 09:07
@dheeraj135  I don't think the error is because of the versioning.
@ndreisg  I went through the code for gstopdf and gstoraster.c for the version your customer is using. gstopdf is simply a wrapper. The options are being [set](https://github.com/OpenPrinting/cups-filters/blob/ad4f69dadba149f43a83f8e9bb7bccc5c28ed20e/filter/gstoraster.c#L265) in the gstoraster.c file

**Comment by ndreisg** [comment] 2019-03-12 14:36
@dheeraj135 I could not reproduce this issue with the latest version. Can be closed. Thanks

**Comment by tillkamppeter** [comment] 2019-03-12 14:45
Closing on OP's request.

**Closed by tillkamppeter** 2019-03-12 14:45 UTC
