### ISSUE TITLE
Can't get my Canon MF8300Cdn to work with CUPS

### ISSUE THREAD

**Issue by kimme1024** [OpenPrinting/cups-filters#234] opened 2020-05-18 14:52 UTC
Hi,

As I want to add AirPrint capability to my Canon MF8300Cdn I found an article that CUPS on a RPi would be a great solution.
I installed everything and the the network printer was immediately recognized.
However there weren't any drivers available. I've uploaded the PPD file that I've found in the driver package for my printer (CNRCUPSMF8300CZK.ppd).
After that I can see my printer with an Idle status.
However when I tried to print I've got the error that restertoufr2 filter wasn't available.
I found this in the driver package and added the file to /usr/lib/cups/filter.
Now I'm getting the state: stopped "Filter failed".
I've been looking for similar issues and solutions but sadly I didn't find anything that worked.

/var/log/cups/error_log:
```
E [18/May/2020:12:30:34 +0100] [Client 6] Unable to encrypt connection: The TLS connection was non-properly terminated.
E [18/May/2020:12:30:53 +0100] [Job 4] Unable to open raster stream - : Broken pipe
E [18/May/2020:12:30:53 +0100] [Job 4] Job stopped due to filter errors; please consult the /var/log/cups/error_log file for details.
D [18/May/2020:12:30:53 +0100] [Job 4] The following messages were recorded from 12:30:39 to 12:30:53
```
Any ideas?
Thanks in advance!

**Comment by zdohnal** [comment] 2020-05-19 04:24
Hi @kimme1024 ,

the core idea of AirPrint and other driverless solutions (IPP Everywhere) is not using any external drivers anymore. 
Meaning you can use the print queue after it was recognized and the printing should work.

Then you can follow several paths:
1) use CUPS temporary queues feature - if your device is capable of driverless printing, then cupsd is capable to create temporary queue for your device whenever you want to print - so print queue is not permanently installed and it appears only when you need it (in print dialogs) and disappears after successful printing (it doesn't eat resource constantly as a permanent queue).
2) create driverless queue manually by 'lpadmin -p <your_print_queue_name> -v <device_uri> -m everywhere -E' - this creates permanent driverless print queue
3) or start cups-browsed service, which does the permanent print queue creation for you

Then please try if driverless solution works for you.

**Comment by kimme1024** [comment] 2020-05-19 19:28
Hi @zdohnal ,

Thanks for your reply!
I tried what you suggested but I probably did something wrong.

This is the output:

```
pi@raspberrypi:~ $ lpadmin -p Canon -v 192.168.1.117 -m everywhere -E
lpadmin: Bad printer URI "192.168.1.117".
pi@raspberrypi:~ $ lpadmin -p Canon -v http://192.168.1.117 -m everywhere -E
lpadmin: Unable to connect to "192.168.1.117:80": Operation now in progress
pi@raspberrypi:~ $ lpadmin -p Canon -v http://192.168.1.117 -m everywhere -E
lpadmin: Unable to query printer: Bad Request
pi@raspberrypi:~ $ lpadmin -p Canon -v dnssd://Canon%20MF8300C%20Series._pdl-datastream._tcp.local/ -m everywhere -E
lpadmin: Unable to query printer: Success
```

First I just tried the IP, didn't work
Then I tried using http, didn't work
Last thing I tried was to use the address that the CUPS interaface used, took a while... but didn't work...

Any ideas?

**Comment by tillkamppeter** [comment] 2020-05-19 19:36
@kimme1024, the printer URI should be something like
```
ipp://192.168.1.117/ipp/print
```
You can run the command
```
driverless
```
and the URIs of available printers should be shown.
The command to create the queue would be
```
lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m everywhere -E
```
If this does not work, there is perhaps an incompatibility of Canon printers. Then try
```
lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m driverless:ipp://192.168.1.117/ipp/print -E
```
Please tell whether this helps and if so, how you got your printer working then.

**Comment by kimme1024** [comment] 2020-05-19 19:44
Hi @tillkamppeter ,

Thanks for the quick reply!

I tried this but it doesn't seem to work.

```
pi@raspberrypi:~ $ lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m everywhere -E
lpadmin: Unable to connect to "192.168.1.117:631": Operation now in progress
pi@raspberrypi:~ $ lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m driverless:ipp://192.168.1.117/ipp/print -E
lpadmin: Unable to open PPD "/tmp/044845ecd87e7": Missing PPD-Adobe-4.x header on line 0.
pi@raspberrypi:~ $ 
```

**Comment by nidhijainpnp** [comment] 2020-07-07 11:36
Hi @kimme1024 
Please tell the version of CUPS you are using.

> ```
> pi@raspberrypi:~ $ lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m everywhere -E
> lpadmin: Unable to connect to "192.168.1.117:631": Operation now in progress
> pi@raspberrypi:~ $ lpadmin -p Canon -v ipp://192.168.1.117/ipp/print -m driverless:ipp://192.168.1.117/ipp/print -E
> lpadmin: Unable to open PPD "/tmp/044845ecd87e7": Missing PPD-Adobe-4.x header on line 0.
> pi@raspberrypi:~ $ 
> ```
From your above logs,it seems that your network printer was not even recognized.Because I was able to reproduce exactly the same logs without having any network printer.
But this contradicts your first comment.Here your network printer was even showing idle status with driver files:
> I installed everything and the the network printer was immediately recognized.However there weren't any drivers available. I've uploaded the PPD file that I've found in the driver package for my printer (CNRCUPSMF8300CZK.ppd).
After that I can see my printer with an Idle status.

This suggests that perhaps,there is incompatibility of AirPrint with this canon model.
Firstly,you can run the command for detailed logs:
```
cupsctl --debug-logging
```
You can try following paths:
1. Run the command :
 ```
driverless
```
This will give you the uri of printer.(If this does not give any output ,jump to alternate path 2,else continue this step.)Then run this:
```
lpadmin -p <print_queue_name> -v $(driverless) -E -m everywhere

```
or
```
lpadmin -p <print_queue_name> -v $(driverless) -m driverless:$(driverless)
```
2.Reach upto the step where your network printer was recognized ,as you have mentioned in your first comment.And if you still got the following previous error:
> ```
>E [18/May/2020:12:30:34 +0100] [Client 6] Unable to encrypt connection: The TLS connection was non-properly terminated.
>E [18/May/2020:12:30:53 +0100] [Job 4] Unable to open raster stream - : Broken pipe
>E [18/May/2020:12:30:53 +0100] [Job 4] Job stopped due to filter errors; please consult the /var/log/cups/error_log file for details.
> ```
Then please check the read-write permission of your ppd file and give the read permission if earlier wasn't given .Most of the time,reading permission is denied,which does not let to open raster-stream.
3.Or you can try to reinstall your printer as mentioned in the solution of exactly the same error ,but for [HP-printers.](https://forums.mageia.org/en/viewtopic.php?f=24&t=10355)
Please attach the detailed error_log files along with your input commands and outputs to give a better insight into further debugging.

**Comment by kimme1024** [comment] 2020-07-07 13:57
Hi!

Thanks for the reply.
As it's been some time since I was fiddling around with this tried reinstalling the printer again with the most recent drivers I could get.

"driverless" doesn't give any output.

When trying to print it states "filter failed".

last page of log:

```
D [07/Jul/2020:14:38:01 +0100] [Client 111] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [07/Jul/2020:14:38:01 +0100] [Client 111] Closing connection.
D [07/Jul/2020:14:38:01 +0100] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [07/Jul/2020:14:38:01 +0100] [Client 94] CGI data ready to be sent.
D [07/Jul/2020:14:38:01 +0100] [Client 94] con->http=0xc914f8
D [07/Jul/2020:14:38:01 +0100] [Client 94] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=7511, file=16
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for CGI data.
D [07/Jul/2020:14:38:01 +0100] [Client 94] con->http=0xc914f8
D [07/Jul/2020:14:38:01 +0100] [Client 94] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=7511, file=16
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for CGI data.
D [07/Jul/2020:14:38:01 +0100] [Client 94] CGI data ready to be sent.
D [07/Jul/2020:14:38:01 +0100] [Client 94] con->http=0xc914f8
D [07/Jul/2020:14:38:01 +0100] [Client 94] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=7511, file=16
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for CGI data.
D [07/Jul/2020:14:38:01 +0100] [Client 94] con->http=0xc914f8
D [07/Jul/2020:14:38:01 +0100] [Client 94] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=7511, file=16
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for CGI data.
D [07/Jul/2020:14:38:01 +0100] [Client 94] CGI data ready to be sent.
D [07/Jul/2020:14:38:01 +0100] [Client 94] con->http=0xc914f8
D [07/Jul/2020:14:38:01 +0100] [Client 94] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=7511, file=16
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for CGI data.
D [07/Jul/2020:14:38:01 +0100] [Client 94] Sending 0-length chunk.
D [07/Jul/2020:14:38:01 +0100] [Client 94] Flushing write buffer.
D [07/Jul/2020:14:38:01 +0100] [Client 94] New state is HTTP_STATE_WAITING
D [07/Jul/2020:14:38:01 +0100] [Client 94] Waiting for request.
D [07/Jul/2020:14:38:01 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
I [07/Jul/2020:14:38:02 +0100] Expiring subscriptions...
D [07/Jul/2020:14:38:49 +0100] [Client 94] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [07/Jul/2020:14:38:49 +0100] [Client 94] Closing connection.
D [07/Jul/2020:14:38:49 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [07/Jul/2020:14:38:49 +0100] [Client 94] Waiting for socket close.
D [07/Jul/2020:14:38:49 +0100] [Client 109] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [07/Jul/2020:14:38:49 +0100] [Client 109] Closing connection.
D [07/Jul/2020:14:38:49 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [07/Jul/2020:14:38:49 +0100] [Client 109] Waiting for socket close.
I [07/Jul/2020:14:38:49 +0100] Expiring subscriptions...
D [07/Jul/2020:14:38:49 +0100] [Job 16] Unloading...
D [07/Jul/2020:14:38:49 +0100] cupsdAddCert: Adding certificate for PID 0
D [07/Jul/2020:14:38:49 +0100] Report: clients=2
D [07/Jul/2020:14:38:49 +0100] Report: jobs=2
D [07/Jul/2020:14:38:49 +0100] Report: jobs-active=1
D [07/Jul/2020:14:38:49 +0100] Report: printers=1
D [07/Jul/2020:14:38:49 +0100] Report: stringpool-string-count=8096
D [07/Jul/2020:14:38:49 +0100] Report: stringpool-alloc-bytes=12848
D [07/Jul/2020:14:38:49 +0100] Report: stringpool-total-bytes=161224
D [07/Jul/2020:14:38:49 +0100] [Client 94] Closing on EOF.
D [07/Jul/2020:14:38:49 +0100] [Client 94] Closing connection.
D [07/Jul/2020:14:38:49 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [07/Jul/2020:14:38:49 +0100] [Client 109] Closing on EOF.
D [07/Jul/2020:14:38:49 +0100] [Client 109] Closing connection.
D [07/Jul/2020:14:38:49 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
I [07/Jul/2020:14:38:50 +0100] Expiring subscriptions...
```

**Comment by nidhijainpnp** [comment] 2020-07-08 13:32
Hi @kimme1024 ,
Could you please tell me the version of CUPS by typing the following command: `apt show cups`
Also please attach the error_log file in .txt format rather than just pasting the last page of it ,of the above logs and also post the terminal output of: 
>When trying to print it states "filter failed".

**Comment by nidhijainpnp** [comment] 2020-07-08 15:44
>I've uploaded the PPD file that I've found in the driver package for my printer (CNRCUPSMF8300CZK.ppd).

Based on this ppd file ,I have run the following command and was not able to reproduce errors
```
PPD=CNRCUPSMF8300CZK.ppd /usr/lib/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf > sample1.pdf
```
So maybe ,it could be the issue of updating the CUPS to latest commits then.It would give me better insight into the errors ,if you could post your commands also(terminal o/p).

**Comment by kimme1024** [comment] 2020-07-08 16:13
Hi @nidhijainpnp ,

You can find the error_log in the attachment.

Version:
```
pi@raspberrypi:~ $ apt show cups
Package: cups
Version: 2.2.10-6+deb10u3
Priority: optional
Section: net
Maintainer: Debian Printing Team <debian-printing@lists.debian.org>
Installed-Size: 1,001 kB
Depends: libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libc6 (>= 2.28), libcups2 (= 2.2.10-6+deb10u3), libcupsimage2 (>= 1.4.0), libgcc1 (>= 1:3.5), libstdc++6 (>= 5), libusb-1.0-0 (>= 2:1.0.8), debconf (>= 0.5) | debconf-2.0, cups-core-drivers (>= 2.2.10-6+deb10u3), cups-daemon (>= 2.2.10-6+deb10u3), poppler-utils, procps, ghostscript, cups-common (>= 2.2.10-6+deb10u3), cups-server-common (>= 2.2.10-6+deb10u3), cups-client (>= 2.2.10-6+deb10u3), cups-ppdc, cups-filters (>= 1.0.24-3~)
Recommends: avahi-daemon, colord, cups-filters (>= 1.0.42) | foomatic-filters, printer-driver-gutenprint, cups-filters (>= 1.0.36) | ghostscript-cups
Suggests: cups-bsd, foomatic-db-compressed-ppds | foomatic-db, printer-driver-hpcups, hplip, cups-pdf, udev, smbclient
Breaks: cups-bsd (<< 1.7.2-3~)
Replaces: cups-bsd (<< 1.7.2-3~)
Homepage: https://www.cups.org/
Download-Size: 348 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
Description: Common UNIX Printing System(tm) - PPD/driver support, web interface
 The Common UNIX Printing System (or CUPS(tm)) is a printing system and
 general replacement for lpd and the like.  It supports the Internet
 Printing Protocol (IPP), and has its own filtering driver model for
 handling various document types.
 .
 This package provides the parts of CUPS which are needed for using printer
 drivers.
```

[error_log.txt](https://github.com/OpenPrinting/cups-filters/files/4891873/error_log.txt)

**Comment by nidhijainpnp** [comment] 2020-07-08 16:56
Hi @kimme1024 
Would you please post here the (i/p and o/p)command you typed on the terminal    ,which had given you the following error of "filter failed"?

**Comment by kimme1024** [comment] 2020-07-08 17:06
Hi @nidhijainpnp 

2.2.10 seems to be the latest version for raspbian.

```
pi@raspberrypi:~ $ sudo apt-get install cups
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cups is already the newest version (2.2.10-6+deb10u3).
0 upgraded, 0 newly installed, 0 to remove and 167 not upgraded.
```

**Comment by nidhijainpnp** [comment] 2020-07-08 17:14
Hi @kimme1024 
Maybe,latest version is not added in apt package.You could install the latest version by cloning the following repository 
(https://github.com/apple/cups) and following the instructions given here [https://github.com/apple/cups/blob/master/INSTALL.md]()

**Comment by tillkamppeter** [comment] 2020-07-08 18:43
@kimme1024, what was your original intention?
1. Your printer is advertised to do AirPrint and you want to use AirPrint (as a client) on your Raspberry Pi to print on your printer.
2. You know that your printer is not capable of driverless (AirPrint for example) printing (and you have even proven this now by the interaction with us). You want to set up CUPS on your Raspberry Pi to set up a print queue with Canon's drivers to be able to print on your printer. Then you want to share this queue on the network so that CUPS is emulating a driverless printer (AirPrint as a server) so that mobile devices and PCs can print without needing a driver by itself.

Please tell us what your intention is.

For (2) you would need to install the complete driver package from Canon, not only the PPD and a filter executable. There can be more filter executables, and auxiliary files like libraries. Note also that most proprietary driver packages made available by manufacturers only work on PCs (Intel or AMD processors, "i386" or "amd64" architectures) but not on Raspberry Pi (ARM processors, "armhf" or "arm64" architectures).
You can probably make your Raspberry Pi only print on your printer if it actually supports driverless printing by itself, supports any common Page Description language like PostScript or PCL, or is supported by some independent free software driver, like Gutenprint. If you get your printer printing from your Raspberry Pi I can help you making the Raspberry Pi being an AirPrint server.

**Comment by kimme1024** [comment] 2020-07-08 20:43
@tillkamppeter, my intention is indeed nr2.

The strange thing is that CUPS immediately finds my printer on the network. When adding it, it only asks voor a PPD file, nothing more so I don't have an option to install a complete driver package (that probably doesn't exist for RPI indeed).
The strange thing is that I can see the printer on my iOS devices and CUPS receives the print jobs from them (so that part does work) and that CUPS does recognise the printer. So it's only the part of sending the job to the printer that's failing.

Oh well, it's not a disaster if it doesn't work but it's a bit stupid to have to send your files to an iMac to be able to print.

**Comment by tillkamppeter** [comment] 2020-07-08 21:15
A last chance is to check if your printer actually does driverless printing by itself by going through its web admin interface and look for options like "IPP", "AirPrint", "Mopria", ... Activate these and see whether this way at least one of the following happens:
1. Your iOS device sees your printer directly without need of your Raspberry Pi.
2. CUPS on your Raspberry Pi can actually set up your printer as a driverless printer and then your iOS device can print through your Raspberry Pi.

Please tell whether this works for you.

I will close this bug report as this is not actually a problem of cups-filters.

**Closed by tillkamppeter** 2020-07-08 21:15 UTC

**Comment by kimme1024** [comment] 2020-07-08 21:31
Hi @tillkamppeter,

Sadly I can't find this in the webinterface.

The only things I found was:
- PDL (Plug&Play) Network: UFRII LT
- LPD is also active on port 515, I tried configuring CUPS via LPD (lpd://IP/queue) but it asks again for the driver after which it gives the filter error again.

Bummer but thanks for investing your time in this!

**Comment by tillkamppeter** [comment] 2020-07-08 21:41
Thank you very much. After googling for your printer model I also got the impression that it is completely proprietary, none of the modern standards for driverless or mobile printing, no standard PDLs, no IPP.
