### ISSUE TITLE
cups-browsed: undefined symbol: ppdgenerator_msg

### ISSUE THREAD

**Issue by biocyberman** [OpenPrinting/cups-filters#43] opened 2018-05-08 09:24 UTC
This is how I checked out, compiled, installed, and ran the program:
```
 cups-filters git:(7e69ffa7) ✗ git branch -v
* (HEAD detached at release-1-20-2) 7e69ffa7 cups-filters 1.20.2 Release
  master                            dcc944cf cups-filters 1.20.3 Release
cups-filters git:(7e69ffa7) ✗ ./configure --enable-poppler-cpp && make -j8
sudo make install
cups-browsed --help
cups-browsed: symbol lookup error: cups-browsed: undefined symbol: ppdgenerator_msg
```
OS:

```
 uname -a
Linux printerhost 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tillkamppeter** [comment] 2018-05-08 09:37
This looks like that cups-browsed is using another libcupsfilters library than the one it came with.
Did you uninstall any old version of cups-filters before installing the new one?
If you build from source, by default cups-browsed and libcupsfilters are installed into subdirectories of /usr/local, whereas distribution packages install into subdirectories of /usr.
You could use
```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
```
to let your from-source installation overwrite your distro's installation.

**Comment by tillkamppeter** [comment] 2018-05-08 20:38
Note that Ubuntu uses systemd to automatically start services, so you need to use the systemd facilities if you want to get cups-browsed automatically started.
I also do not know whether the use of stow can cause any problem here.
I am closing this issue as this is most probably not a bug in cups-filters.

**Closed by tillkamppeter** 2018-05-08 20:38 UTC
