### ISSUE TITLE
driverless fails with "ERROR: ippfind (PID ...) stopped with status 1!" possibly false alarm?

### ISSUE THREAD

**Issue by jsmeix** [OpenPrinting/cups-filters#375] opened 2021-06-08 08:31 UTC
I use cups-filters 1.28.8 with CUPS 2.3.3op2 on openSUSE Leap 15.2 x86_64.

In /var/log/cups/error_log I noticed that after `lpinfo -v` the following appears (excerpt)
```
D [08/Jun/2021:08:57:35 +0200] [cups-deviced] Started backend /usr/lib/cups/backend/driverless (PID 6729)
D [08/Jun/2021:08:57:35 +0200] [CGI] Started ippfind (PID 6746)
E [08/Jun/2021:08:57:35 +0200] [CGI] ippfind (PID 6746) stopped with status 1!
E [08/Jun/2021:08:57:35 +0200] [cups-deviced] PID 6729 (driverless) stopped with status 1!
```

Running `driverlesss` directly as root results
```
# /usr/bin/driverless --debug
DEBUG: Started ippfind (PID 7668)
ERROR: ippfind (PID 7668) stopped with status 1!
```
but calling plain `ippfind` directly as root works and results
```
# /usr/bin/ippfind
ipp://linux-h9wr.local:631/printers/fr
ipp://linux-h9wr.local:631/printers/ps
ipp://linux-h9wr.local:631/printers/testq
```
`fr` `ps` and `testq` are some local queues for some (other) tests.

Unfortunately the `driverless` debug mode doesn't tell anything more
why `ippfind` failed so I guessed it fails because `driverless` calls `ippfind`
in a special way which fails so I tried some more debugging via
```
# /usr/bin/driverless --debug & sleep 0.2 ; ps -o pid,user,args -C ippfind | cat -n ; sleep 3
[1] 7820
DEBUG: Started ippfind (PID 7822)
     1    PID USER     COMMAND
     2   7822 root     ippfind -T 0 _ipps._tcp _ipp._tcp ! --txt printer-type --and ( --txt-pdl image/pwg-raster --or --txt-pdl application/PCLm --or --txt-pdl image/urf --or --txt-pdl application/pdf ) -x echo -en {service_scheme}?{service_name}?{service_domain}?  ;
ERROR: ippfind (PID 7822) stopped with status 1!
[1]+  Exit 1                  /usr/bin/driverless --debug
```
which shows how `driverless` calls `ippfind`
but of course that cannot show how `ippfind` fails
so I tried to run such an `ippfind` command directly
("man ippfind" doesn't tell anything about 'verbose' or 'debug')
```
# ippfind -T 0 _ipps._tcp _ipp._tcp --not --txt printer-type --and \( --txt-pdl image/pwg-raster --or --txt-pdl application/PCLm --or --txt-pdl image/urf --or --txt-pdl application/pdf \) -x echo -en '{service_scheme} {service_name} {service_domain}' \;
# echo $?
1
```
so I got exit code 1 from `ippfind` which seems to be not an actual error exit
because "man ippfind" reads
```
EXIT STATUS
ippfind returns
0 if the result for all processed expressions is true,
1 if the result of any processed expression is false,
2 if browsing or any query or resolution failed,
3 if an undefined option or invalid expression was specified, and
4 if it ran out of memory.
```
and I think when an expression result is false it basically means "not found"
but that is not an error of `ippfind` so perhaps in the end all is well
and the message
```
ERROR: ippfind (PID ...) stopped with status 1!
```
is only misleading false alarm and
when `driverless` runs `ippfind` its exit code `1` should be ignored
or considered as some special kind of "not found" success
in `list_printers` in utils/driverless.c ?

**Comment by zdohnal** [comment] 2021-06-08 08:39
Hi Johannes,

please check my email on printing-architecture mailing list - Solomon got into the same situation and IMO it is an expected behavior, if the queues you found by ippfind are remote cups queues and my assumption about driverless are correct.

I wrote the email to get a verification from Till.

**Comment by zdohnal** [comment] 2021-06-08 08:45
> ```
> ERROR: ippfind (PID ...) stopped with status 1!
> ```
> 
> is only misleading false alarm and
> when `driverless` runs `ippfind` its exit code `1` should be ignored
> or considered as some special kind of "not found" success
> in `list_printers` in utils/driverless.c ?

If you propose to remove this error message and just return '1' as an exit code, then I agree. If ippfind finds nothing, driverless shouldn't state it as an error.

**Comment by jsmeix** [comment] 2021-06-08 08:55
Hello Zdenek
I think you mean
https://lists.linuxfoundation.org/pipermail/printing-architecture/2021/004047.html

I think this is something different.

My issue here is that I think when `ippfind` exits with exit code 1
it seems to be not an actual error (as far as I understand "man ippfind")
so `ippfind`exit code 1 should not be treated as an error so that
in particular `driverless` should not be `stopped with status 1`.

I think when `ippfind` exits with exit code 1 it behaves like
```
# echo foo | grep bar

# echo $?
1
```
where the caller of `grep` must decide if its exit code 1 means
an error for the caller or if "not found" is an expected successful outcome.

**Comment by zdohnal** [comment] 2021-06-08 09:05
Aha, I'm sorry - I thought one of the part of the problem is that driverless returns nothing but ippfind finds queues.

Ad the actual problem - IMO the return value from ippfind should propagate into driverless - meaning ippfind returns 1 -> driverless returns 1.

**Comment by jsmeix** [comment] 2021-06-08 09:05
https://bugzilla.redhat.com/show_bug.cgi?id=1954469#c2
reads (excerpt)
```
Dropping the '!' seems to make things work for me.  Not sure why it's there.
```
so I tried the above `ippfind` command without the `--not`
(and a bit different `echo` for better readability here):
```
# ippfind -T 0 _ipps._tcp _ipp._tcp --txt printer-type --and \( --txt-pdl image/pwg-raster --or --txt-pdl application/PCLm --or --txt-pdl image/urf --or --txt-pdl application/pdf \) -x echo '{service_scheme} {service_name} {service_domain}' \; ; echo $?
=ipps fr @ linux-h9wr local
=ipp fr @ linux-h9wr local
=ipps ps @ linux-h9wr local
=ipp ps @ linux-h9wr local
0
```

I guess the `--not` or `!` is there to intentionally exclude such found IPP printers
from what `driverless` autodetects.

**Comment by jsmeix** [comment] 2021-06-08 09:16
https://lists.linuxfoundation.org/pipermail/printing-architecture/2021/004048.html
explains it all

Thank you @tillkamppeter !

**Comment by tillkamppeter** [comment] 2021-06-08 09:40
Fixed in commit 78b6b2c9 on master. Thanks for the bug report.

Now `driverless` exits with 0 if no suitable printer got found, according to CUPS standards.

**Closed by tillkamppeter** 2021-06-08 09:40 UTC

**Comment by zdohnal** [comment] 2021-06-08 09:46
@tillkamppeter just implementation question - can we do this just by assigning 0 after the getting exit status from ippfind, if the ippfind returns 1?
It will be only two lines change.

**Comment by tillkamppeter** [comment] 2021-06-08 10:32
@zdohnal, I switched to your method now, as mine also interfered with some other error condition. Thank you very much.

**Comment by jsmeix** [comment] 2021-06-08 11:00
Interesting to see that what looks on first glance like a
quick and dirty hack `if (exit_status == 1) exit_status = 0;`
is actually the simplest and most straightforward solution in this case.
@zdohnal @tillkamppeter thank you both for the proper fix!
