### ISSUE TITLE
Multiple file type printing issue(DOC,TXT,xml,xls,ppt,ppd)

### ISSUE THREAD

**Issue by chennasudhakar** [OpenPrinting/cups-filters#420] opened 2021-09-03 07:28 UTC
When i try to print word document in linux i am getting following error
Xls:
Commnd=lp -d Hold_printer /home/sudhakar/Text2-Image-barcode-Folders.xls
Error=lp: Unsupported document-format "application/msword".

Docx:
Command = lp -d Hold_printer /home/efi/test.docx 
Error =lp: Unsupported document-format "application/vnd.openxmlformats-officedocument.wordprocessingml.document".

Please help on the above two issues in Linux 

Thanks
C.Sudhakar

**Comment by jsmeix** [comment] 2021-09-03 08:20
@chennasudhakar 
only FYI as some general background information see
https://en.opensuse.org/SDB:Printing_from_Windows_to_Linux

**Comment by chennasudhakar** [comment] 2021-09-03 09:09
i am writing some printer driver their i am using following api

if (cupsStartDestDocument(CUPS_HTTP_DEFAULT, dest, dinfo, job_id, print_file, CUPS_FORMAT_AUTO, 0, NULL, 1) != HTTP_STATUS_CONTINUE)

One of the argument for the above api is MIME.TYPE 
cups supporting following MIME.TYPES for the above api
#  define CUPS_FORMAT_AUTO              "application/octet-stream"
#  define CUPS_FORMAT_COMMAND           "application/vnd.cups-command"
#  define CUPS_FORMAT_JPEG              "image/jpeg"
#  define CUPS_FORMAT_PDF               "application/pdf"
#  define CUPS_FORMAT_POSTSCRIPT        "application/postscript"
#  define CUPS_FORMAT_RAW               "application/vnd.cups-raw"
#  define CUPS_FORMAT_TEXT              "text/plain"

So which  one i need to use to print any document without any error in linux

**Comment by debiantriage** [comment] 2021-09-04 14:32
@chennasudhakar I cannot help with writing your prospective printer driver but maybe section 9 at

 https://wiki.debian.org/CUPSTea4CUPS

is of use.

**Comment by tillkamppeter** [comment] 2021-09-04 14:58
Note that you cannot print any arbitrary application document file with CUPS. Usually you open such a file with the appropriate application and print from inside the application using "File" -> "Print" or Ctrl+P. This converts the document into PDF and sends the PDF file to CUPS. CUPS can convert PDF into whatever the printer needs.

As you do not have Microsoft Office under Linux, open (and print) the Microsoft Office files with LibreOffice.

This is not a bug, but expected behavior. Closing ...

(But we have no objections if you write a filter for direct printing of Office documents though ...)

**Closed by tillkamppeter** 2021-09-04 14:58 UTC
